name: Get PR last Deploy Status
author: gp@envoy.com
description: Fetches a PR's last deploy status and outputs it
branding:
  icon: git-pull-request
  color: blue
inputs:
  repository:
    description: Git Repository name
    required: true
  environment:
    description: Pull request deployment environment name
    required: true
outputs:
  status:
    description: Status of the Pull requests last deployed status of an environment
runs:
  using: node16
  main: dist/index.js
